SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

INSERT INTO `countries` (`id`, `name`, `code`, `flag`, `capital`) VALUES
(1, 'Afghanistan', 'AF', '🇦🇫', 'Kabul'),
(2, 'Aland Islands', 'AX', '🇦🇽', 'Mariehamn'),
(3, 'Albania', 'AL', '🇦🇱', 'Tirana'),
(4, 'Algeria', 'DZ', '🇩🇿', 'Algiers'),
(5, 'American Samoa', 'AS', '🇦🇸', 'Pago Pago'),
(6, 'Andorra', 'AD', '🇦🇩', 'Andorra la Vella'),
(7, 'Angola', 'AO', '🇦🇴', 'Luanda'),
(8, 'Anguilla', 'AI', '🇦🇮', 'The Valley'),
(9, 'Antarctica', 'AQ', '🇦🇶', ''),
(10, 'Antigua And Barbuda', 'AG', '🇦🇬', 'St. John\'s'),
(11, 'Argentina', 'AR', '🇦🇷', 'Buenos Aires'),
(12, 'Armenia', 'AM', '🇦🇲', 'Yerevan'),
(13, 'Aruba', 'AW', '🇦🇼', 'Oranjestad'),
(14, 'Australia', 'AU', '🇦🇺', 'Canberra'),
(15, 'Austria', 'AT', '🇦🇹', 'Vienna'),
(16, 'Azerbaijan', 'AZ', '🇦🇿', 'Baku'),
(17, 'Bahamas The', 'BS', '🇧🇸', 'Nassau'),
(18, 'Bahrain', 'BH', '🇧🇭', 'Manama'),
(19, 'Bangladesh', 'BD', '🇧🇩', 'Dhaka'),
(20, 'Barbados', 'BB', '🇧🇧', 'Bridgetown'),
(21, 'Belarus', 'BY', '🇧🇾', 'Minsk'),
(22, 'Belgium', 'BE', '🇧🇪', 'Brussels'),
(23, 'Belize', 'BZ', '🇧🇿', 'Belmopan'),
(24, 'Benin', 'BJ', '🇧🇯', 'Porto-Novo'),
(25, 'Bermuda', 'BM', '🇧🇲', 'Hamilton'),
(26, 'Bhutan', 'BT', '🇧🇹', 'Thimphu'),
(27, 'Bolivia', 'BO', '🇧🇴', 'Sucre'),
(28, 'Bosnia and Herzegovina', 'BA', '🇧🇦', 'Sarajevo'),
(29, 'Botswana', 'BW', '🇧🇼', 'Gaborone'),
(30, 'Bouvet Island', 'BV', '🇧🇻', ''),
(31, 'Brazil', 'BR', '🇧🇷', 'Brasilia'),
(32, 'British Indian Ocean Territory', 'IO', '🇮🇴', 'Diego Garcia'),
(33, 'Brunei', 'BN', '🇧🇳', 'Bandar Seri Begawan'),
(34, 'Bulgaria', 'BG', '🇧🇬', 'Sofia'),
(35, 'Burkina Faso', 'BF', '🇧🇫', 'Ouagadougou'),
(36, 'Burundi', 'BI', '🇧🇮', 'Bujumbura'),
(37, 'Cambodia', 'KH', '🇰🇭', 'Phnom Penh'),
(38, 'Cameroon', 'CM', '🇨🇲', 'Yaounde'),
(39, 'Canada', 'CA', '🇨🇦', 'Ottawa'),
(40, 'Cape Verde', 'CV', '🇨🇻', 'Praia'),
(41, 'Cayman Islands', 'KY', '🇰🇾', 'George Town'),
(42, 'Central African Republic', 'CF', '🇨🇫', 'Bangui'),
(43, 'Chad', 'TD', '🇹🇩', 'N\'Djamena'),
(44, 'Chile', 'CL', '🇨🇱', 'Santiago'),
(45, 'China', 'CN', '🇨🇳', 'Beijing'),
(46, 'Christmas Island', 'CX', '🇨🇽', 'Flying Fish Cove'),
(47, 'Cocos (Keeling) Islands', 'CC', '🇨🇨', 'West Island'),
(48, 'Colombia', 'CO', '🇨🇴', 'Bogota'),
(49, 'Comoros', 'KM', '🇰🇲', 'Moroni'),
(50, 'Congo', 'CG', '🇨🇬', 'Brazzaville'),
(51, 'Congo The Democratic Republic Of The', 'CD', '🇨🇩', 'Kinshasa'),
(52, 'Cook Islands', 'CK', '🇨🇰', 'Avarua'),
(53, 'Costa Rica', 'CR', '🇨🇷', 'San Jose'),
(54, 'Cote D\'Ivoire (Ivory Coast)', 'CI', '🇨🇮', 'Yamoussoukro'),
(55, 'Croatia (Hrvatska)', 'HR', '🇭🇷', 'Zagreb'),
(56, 'Cuba', 'CU', '🇨🇺', 'Havana'),
(57, 'Cyprus', 'CY', '🇨🇾', 'Nicosia'),
(58, 'Czech Republic', 'CZ', '🇨🇿', 'Prague'),
(59, 'Denmark', 'DK', '🇩🇰', 'Copenhagen'),
(60, 'Djibouti', 'DJ', '🇩🇯', 'Djibouti'),
(61, 'Dominica', 'DM', '🇩🇲', 'Roseau'),
(62, 'Dominican Republic', 'DO', '🇩🇴', 'Santo Domingo'),
(63, 'East Timor', 'TL', '🇹🇱', 'Dili'),
(64, 'Ecuador', 'EC', '🇪🇨', 'Quito'),
(65, 'Egypt', 'EG', '🇪🇬', 'Cairo'),
(66, 'El Salvador', 'SV', '🇸🇻', 'San Salvador'),
(67, 'Equatorial Guinea', 'GQ', '🇬🇶', 'Malabo'),
(68, 'Eritrea', 'ER', '🇪🇷', 'Asmara'),
(69, 'Estonia', 'EE', '🇪🇪', 'Tallinn'),
(70, 'Ethiopia', 'ET', '🇪🇹', 'Addis Ababa'),
(71, 'Falkland Islands', 'FK', '🇫🇰', 'Stanley'),
(72, 'Faroe Islands', 'FO', '🇫🇴', 'Torshavn'),
(73, 'Fiji Islands', 'FJ', '🇫🇯', 'Suva'),
(74, 'Finland', 'FI', '🇫🇮', 'Helsinki'),
(75, 'France', 'FR', '🇫🇷', 'Paris'),
(76, 'French Guiana', 'GF', '🇬🇫', 'Cayenne'),
(77, 'French Polynesia', 'PF', '🇵🇫', 'Papeete'),
(78, 'French Southern Territories', 'TF', '🇹🇫', 'Port-aux-Francais'),
(79, 'Gabon', 'GA', '🇬🇦', 'Libreville'),
(80, 'Gambia The', 'GM', '🇬🇲', 'Banjul'),
(81, 'Georgia', 'GE', '🇬🇪', 'Tbilisi'),
(82, 'Germany', 'DE', '🇩🇪', 'Berlin'),
(83, 'Ghana', 'GH', '🇬🇭', 'Accra'),
(84, 'Gibraltar', 'GI', '🇬🇮', 'Gibraltar'),
(85, 'Greece', 'GR', '🇬🇷', 'Athens'),
(86, 'Greenland', 'GL', '🇬🇱', 'Nuuk'),
(87, 'Grenada', 'GD', '🇬🇩', 'St. George\'s'),
(88, 'Guadeloupe', 'GP', '🇬🇵', 'Basse-Terre'),
(89, 'Guam', 'GU', '🇬🇺', 'Hagatna'),
(90, 'Guatemala', 'GT', '🇬🇹', 'Guatemala City'),
(91, 'Guernsey and Alderney', 'GG', '🇬🇬', 'St Peter Port'),
(92, 'Guinea', 'GN', '🇬🇳', 'Conakry'),
(93, 'Guinea-Bissau', 'GW', '🇬🇼', 'Bissau'),
(94, 'Guyana', 'GY', '🇬🇾', 'Georgetown'),
(95, 'Haiti', 'HT', '🇭🇹', 'Port-au-Prince'),
(96, 'Heard and McDonald Islands', 'HM', '🇭🇲', ''),
(97, 'Honduras', 'HN', '🇭🇳', 'Tegucigalpa'),
(98, 'Hong Kong S.A.R.', 'HK', '🇭🇰', 'Hong Kong'),
(99, 'Hungary', 'HU', '🇭🇺', 'Budapest'),
(100, 'Iceland', 'IS', '🇮🇸', 'Reykjavik'),
(101, 'India', 'IN', '🇮🇳', 'New Delhi'),
(102, 'Indonesia', 'ID', '🇮🇩', 'Jakarta'),
(103, 'Iran', 'IR', '🇮🇷', 'Tehran'),
(104, 'Iraq', 'IQ', '🇮🇶', 'Baghdad'),
(105, 'Ireland', 'IE', '🇮🇪', 'Dublin'),
(106, 'Israel', 'IL', '🇮🇱', 'Jerusalem'),
(107, 'Italy', 'IT', '🇮🇹', 'Rome'),
(108, 'Jamaica', 'JM', '🇯🇲', 'Kingston'),
(109, 'Japan', 'JP', '🇯🇵', 'Tokyo'),
(110, 'Jersey', 'JE', '🇯🇪', 'Saint Helier'),
(111, 'Jordan', 'JO', '🇯🇴', 'Amman'),
(112, 'Kazakhstan', 'KZ', '🇰🇿', 'Astana'),
(113, 'Kenya', 'KE', '🇰🇪', 'Nairobi'),
(114, 'Kiribati', 'KI', '🇰🇮', 'Tarawa'),
(115, 'Korea North', 'KP', '🇰🇵', 'Pyongyang'),
(116, 'Korea South', 'KR', '🇰🇷', 'Seoul'),
(117, 'Kuwait', 'KW', '🇰🇼', 'Kuwait City'),
(118, 'Kyrgyzstan', 'KG', '🇰🇬', 'Bishkek'),
(119, 'Laos', 'LA', '🇱🇦', 'Vientiane'),
(120, 'Latvia', 'LV', '🇱🇻', 'Riga'),
(121, 'Lebanon', 'LB', '🇱🇧', 'Beirut'),
(122, 'Lesotho', 'LS', '🇱🇸', 'Maseru'),
(123, 'Liberia', 'LR', '🇱🇷', 'Monrovia'),
(124, 'Libya', 'LY', '🇱🇾', 'Tripolis'),
(125, 'Liechtenstein', 'LI', '🇱🇮', 'Vaduz'),
(126, 'Lithuania', 'LT', '🇱🇹', 'Vilnius'),
(127, 'Luxembourg', 'LU', '🇱🇺', 'Luxembourg'),
(128, 'Macau S.A.R.', 'MO', '🇲🇴', 'Macao'),
(129, 'Macedonia', 'MK', '🇲🇰', 'Skopje'),
(130, 'Madagascar', 'MG', '🇲🇬', 'Antananarivo'),
(131, 'Malawi', 'MW', '🇲🇼', 'Lilongwe'),
(132, 'Malaysia', 'MY', '🇲🇾', 'Kuala Lumpur'),
(133, 'Maldives', 'MV', '🇲🇻', 'Male'),
(134, 'Mali', 'ML', '🇲🇱', 'Bamako'),
(135, 'Malta', 'MT', '🇲🇹', 'Valletta'),
(136, 'Man (Isle of)', 'IM', '🇮🇲', 'Douglas, Isle of Man'),
(137, 'Marshall Islands', 'MH', '🇲🇭', 'Majuro'),
(138, 'Martinique', 'MQ', '🇲🇶', 'Fort-de-France'),
(139, 'Mauritania', 'MR', '🇲🇷', 'Nouakchott'),
(140, 'Mauritius', 'MU', '🇲🇺', 'Port Louis'),
(141, 'Mayotte', 'YT', '🇾🇹', 'Mamoudzou'),
(142, 'Mexico', 'MX', '🇲🇽', 'Mexico City'),
(143, 'Micronesia', 'FM', '🇫🇲', 'Palikir'),
(144, 'Moldova', 'MD', '🇲🇩', 'Chisinau'),
(145, 'Monaco', 'MC', '🇲🇨', 'Monaco'),
(146, 'Mongolia', 'MN', '🇲🇳', 'Ulan Bator'),
(147, 'Montenegro', 'ME', '🇲🇪', 'Podgorica'),
(148, 'Montserrat', 'MS', '🇲🇸', 'Plymouth'),
(149, 'Morocco', 'MA', '🇲🇦', 'Rabat'),
(150, 'Mozambique', 'MZ', '🇲🇿', 'Maputo'),
(151, 'Myanmar', 'MM', '🇲🇲', 'Nay Pyi Taw'),
(152, 'Namibia', 'NA', '🇳🇦', 'Windhoek'),
(153, 'Nauru', 'NR', '🇳🇷', 'Yaren'),
(154, 'Nepal', 'NP', '🇳🇵', 'Kathmandu'),
(155, 'Netherlands Antilles', 'AN', NULL, ''),
(156, 'Netherlands The', 'NL', '🇳🇱', 'Amsterdam'),
(157, 'New Caledonia', 'NC', '🇳🇨', 'Noumea'),
(158, 'New Zealand', 'NZ', '🇳🇿', 'Wellington'),
(159, 'Nicaragua', 'NI', '🇳🇮', 'Managua'),
(160, 'Niger', 'NE', '🇳🇪', 'Niamey'),
(161, 'Nigeria', 'NG', '🇳🇬', 'Abuja'),
(162, 'Niue', 'NU', '🇳🇺', 'Alofi'),
(163, 'Norfolk Island', 'NF', '🇳🇫', 'Kingston'),
(164, 'Northern Mariana Islands', 'MP', '🇲🇵', 'Saipan'),
(165, 'Norway', 'NO', '🇳🇴', 'Oslo'),
(166, 'Oman', 'OM', '🇴🇲', 'Muscat'),
(167, 'Pakistan', 'PK', '🇵🇰', 'Islamabad'),
(168, 'Palau', 'PW', '🇵🇼', 'Melekeok'),
(169, 'Palestinian Territory Occupied', 'PS', '🇵🇸', 'East Jerusalem'),
(170, 'Panama', 'PA', '🇵🇦', 'Panama City'),
(171, 'Papua new Guinea', 'PG', '🇵🇬', 'Port Moresby'),
(172, 'Paraguay', 'PY', '🇵🇾', 'Asuncion'),
(173, 'Peru', 'PE', '🇵🇪', 'Lima'),
(174, 'Philippines', 'PH', '🇵🇭', 'Manila'),
(175, 'Pitcairn Island', 'PN', '🇵🇳', 'Adamstown'),
(176, 'Poland', 'PL', '🇵🇱', 'Warsaw'),
(177, 'Portugal', 'PT', '🇵🇹', 'Lisbon'),
(178, 'Puerto Rico', 'PR', '🇵🇷', 'San Juan'),
(179, 'Qatar', 'QA', '🇶🇦', 'Doha'),
(180, 'Reunion', 'RE', '🇷🇪', 'Saint-Denis'),
(181, 'Romania', 'RO', '🇷🇴', 'Bucharest'),
(182, 'Russia', 'RU', '🇷🇺', 'Moscow'),
(183, 'Rwanda', 'RW', '🇷🇼', 'Kigali'),
(184, 'Saint Helena', 'SH', '🇸🇭', 'Jamestown'),
(185, 'Saint Kitts And Nevis', 'KN', '🇰🇳', 'Basseterre'),
(186, 'Saint Lucia', 'LC', '🇱🇨', 'Castries'),
(187, 'Saint Pierre and Miquelon', 'PM', '🇵🇲', 'Saint-Pierre'),
(188, 'Saint Vincent And The Grenadines', 'VC', '🇻🇨', 'Kingstown'),
(189, 'Saint-Barthelemy', 'BL', '🇧🇱', 'Gustavia'),
(190, 'Saint-Martin (French part)', 'MF', '🇲🇫', 'Marigot'),
(191, 'Samoa', 'WS', '🇼🇸', 'Apia'),
(192, 'San Marino', 'SM', '🇸🇲', 'San Marino'),
(193, 'Sao Tome and Principe', 'ST', '🇸🇹', 'Sao Tome'),
(194, 'Saudi Arabia', 'SA', '🇸🇦', 'Riyadh'),
(195, 'Senegal', 'SN', '🇸🇳', 'Dakar'),
(196, 'Serbia', 'RS', '🇷🇸', 'Belgrade'),
(197, 'Seychelles', 'SC', '🇸🇨', 'Victoria'),
(198, 'Sierra Leone', 'SL', '🇸🇱', 'Freetown'),
(199, 'Singapore', 'SG', '🇸🇬', 'Singapur'),
(200, 'Slovakia', 'SK', '🇸🇰', 'Bratislava'),
(201, 'Slovenia', 'SI', '🇸🇮', 'Ljubljana'),
(202, 'Solomon Islands', 'SB', '🇸🇧', 'Honiara'),
(203, 'Somalia', 'SO', '🇸🇴', 'Mogadishu'),
(204, 'South Africa', 'ZA', '🇿🇦', 'Pretoria'),
(205, 'South Georgia', 'GS', '🇬🇸', 'Grytviken'),
(206, 'South Sudan', 'SS', '🇸🇸', 'Juba'),
(207, 'Spain', 'ES', '🇪🇸', 'Madrid'),
(208, 'Sri Lanka', 'LK', '🇱🇰', 'Colombo'),
(209, 'Sudan', 'SD', '🇸🇩', 'Khartoum'),
(210, 'Suriname', 'SR', '🇸🇷', 'Paramaribo'),
(211, 'Svalbard And Jan Mayen Islands', 'SJ', '🇸🇯', 'Longyearbyen'),
(212, 'Swaziland', 'SZ', '🇸🇿', 'Mbabane'),
(213, 'Sweden', 'SE', '🇸🇪', 'Stockholm'),
(214, 'Switzerland', 'CH', '🇨🇭', 'Berne'),
(215, 'Syria', 'SY', '🇸🇾', 'Damascus'),
(216, 'Taiwan', 'TW', '🇹🇼', 'Taipei'),
(217, 'Tajikistan', 'TJ', '🇹🇯', 'Dushanbe'),
(218, 'Tanzania', 'TZ', '🇹🇿', 'Dodoma'),
(219, 'Thailand', 'TH', '🇹🇭', 'Bangkok'),
(220, 'Togo', 'TG', '🇹🇬', 'Lome'),
(221, 'Tokelau', 'TK', '🇹🇰', ''),
(222, 'Tonga', 'TO', '🇹🇴', 'Nuku\'alofa'),
(223, 'Trinidad And Tobago', 'TT', '🇹🇹', 'Port of Spain'),
(224, 'Tunisia', 'TN', '🇹🇳', 'Tunis'),
(225, 'Turkey', 'TR', '🇹🇷', 'Ankara'),
(226, 'Turkmenistan', 'TM', '🇹🇲', 'Ashgabat'),
(227, 'Turks And Caicos Islands', 'TC', '🇹🇨', 'Cockburn Town'),
(228, 'Tuvalu', 'TV', '🇹🇻', 'Funafuti'),
(229, 'Uganda', 'UG', '🇺🇬', 'Kampala'),
(230, 'Ukraine', 'UA', '🇺🇦', 'Kiev'),
(231, 'United Arab Emirates', 'AE', '🇦🇪', 'Abu Dhabi'),
(232, 'United Kingdom', 'GB', '🇬🇧', 'London'),
(233, 'United States', 'US', '🇺🇸', 'Washington'),
(234, 'United States Minor Outlying Islands', 'UM', '🇺🇲', ''),
(235, 'Uruguay', 'UY', '🇺🇾', 'Montevideo'),
(236, 'Uzbekistan', 'UZ', '🇺🇿', 'Tashkent'),
(237, 'Vanuatu', 'VU', '🇻🇺', 'Port Vila'),
(238, 'Vatican City State (Holy See)', 'VA', '🇻🇦', 'Vatican City'),
(239, 'Venezuela', 'VE', '🇻🇪', 'Caracas'),
(240, 'Vietnam', 'VN', '🇻🇳', 'Hanoi'),
(241, 'Virgin Islands (British)', 'VG', '🇻🇬', 'Road Town'),
(242, 'Virgin Islands (US)', 'VI', '🇻🇮', 'Charlotte Amalie'),
(243, 'Wallis And Futuna Islands', 'WF', '🇼🇫', 'Mata Utu'),
(244, 'Western Sahara', 'EH', '🇪🇭', 'El-Aaiun'),
(245, 'Yemen', 'YE', '🇾🇪', 'Sanaa'),
(246, 'Zambia', 'ZM', '🇿🇲', 'Lusaka'),
(247, 'Zimbabwe', 'ZW', '🇿🇼', 'Harare');

SET FOREIGN_KEY_CHECKS=1;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
